# Generated by Django 2.1.2 on 2018-11-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Company Name')),
                ('address1', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address2')),
                ('address3', models.CharField(blank=True, max_length=64, null=True, verbose_name='Address3')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State-Province')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip or Postal Code')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('extension', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ext.')),
                ('website', models.CharField(blank=True, max_length=64, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
    ]
