# Generated by Django 2.1.2 on 2018-10-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='coutnry',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='state/prov',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='zip-postal',
        ),
        migrations.AddField(
            model_name='factory',
            name='state',
            field=models.CharField(blank=True, max_length=64, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='factory',
            name='zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
