# Generated by Django 2.1.2 on 2018-10-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20181019_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='contact_name',
            field=models.ForeignKey(blank=True, max_length=64, null=True, on_delete='CASCADE', to='factory.FactoryContact'),
        ),
    ]
