# Generated by Django 2.1.2 on 2018-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_auto_20181019_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'ordering': ['contact_name', 'name', 'address1']},
        ),
        migrations.AddField(
            model_name='factory',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
    ]
