# Generated by Django 2.1 on 2018-09-28 15:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todos_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='todos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='null'),
            preserve_default=False,
        ),
    ]
