# Generated by Django 2.1 on 2018-09-28 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todos_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[dict]),
        ),
    ]
