# Generated by Django 2.1 on 2018-09-28 16:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20180928_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='[]'),
        ),
    ]
