# Generated by Django 2.1 on 2018-10-03 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20180928_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='set_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='todos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
