# Generated by Django 2.1 on 2018-10-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20181003_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosgroup',
            name='group_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
