# Generated by Django 2.1.2 on 2018-10-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181004_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_tasks',
            field=models.ManyToManyField(blank=True, null=True, to='orders.OrderTasks'),
        ),
    ]
