# Generated by Django 2.1.2 on 2018-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertasks',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='orders.Orders'),
        ),
    ]
