# Generated by Django 2.1.2 on 2018-10-04 20:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordertasks_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertasks',
            name='tasks',
        ),
        migrations.AddField(
            model_name='ordertasks',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
