# Generated by Django 2.1.2 on 2018-10-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181004_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertasks',
            old_name='data',
            new_name='todos',
        ),
    ]
