# Generated by Django 2.1.2 on 2018-10-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181004_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertasks',
            name='set_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordertasks',
            name='todos_group',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
