# Generated by Django 2.1.2 on 2018-10-12 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181004_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Due Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
