# Generated by Django 2.1.2 on 2018-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20181016_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertasks',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
