# Generated by Django 2.1.2 on 2018-10-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20181016_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
