# Generated by Django 2.1.2 on 2018-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20181019_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='factory_ship_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ship to Factory Date'),
        ),
    ]
