# Generated by Django 2.1.2 on 2018-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20181019_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.FloatField(blank=True, null=True, verbose_name='Order Qty'),
        ),
    ]
