# Generated by Django 2.1.2 on 2018-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20181023_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='slug',
        ),
    ]
